Repository skillrecordings/egghead-next, pull requests merged in 2020-12, with the labels that each got.

#191 optimize lesson page loading
  src/components/pages/lessons/LessonInfo.tsx
  src/components/pages/lessons/overlay/next-up-overlay.tsx
  src/context/viewer-context.tsx
  src/hooks/use-next-up-data.tsx
  src/pages/lessons/[slug].tsx
  src/utils/auth.ts
  src/utils/fetcher.ts
Labels: help wanted

#205 Changes to the codemod post
  src/pages/learn/javascript/codemods-with-babel-plugins/index.mdx
Labels: copy edit

#207 Adding Filip Hric's article on Handling copy and paste in Cypress
  src/layouts/ultimate-guide.tsx
  src/pages/learn/javascript/handling-copy-and-paste-in-cypress/index.mdx
Labels: copy edit

#220 handle absent Course image on NextUp overlay
  src/components/pages/lessons/overlay/next-up-overlay.tsx
Labels: bug

#212 Rate Course overlay: initial step
  src/components/EggheadPlayer/use-egghead-player.ts
  src/components/pages/lessons/AutoplayToggle.tsx
  src/components/pages/lessons/LessonInfo.tsx
  src/components/pages/lessons/overlay/next-up-overlay.tsx
  src/components/pages/lessons/overlay/rate-course-overlay.tsx
  src/pages/lessons/[slug].tsx
Labels: help wanted
