Repository skillrecordings/egghead-next, pull requests merged in 2022-08, with the labels that each got.

#1158 fix: the production process state validation error
  studio/schemas/documents/resource.js
  studio/schemas/objects/production-process-state.js
Labels: bug

#1161 chore: Improve the type safety of php-collection-page-layout.tsx
  src/components/layouts/php-collection-page-layout.tsx
Labels: chore

#1184 feat: use zod to validate and type Course/Lesson data from Course Builder
  package.json
  src/pages/api/sanity/lessons/create.ts
  src/pages/upload/index.tsx
  src/types.ts
  yarn.lock
Labels: RFC
